#!/usr/bin/env bash

# Start Apache service
service apache2 start

# Check if Apache is running
if systemctl is-active --quiet apache2; then
    echo "apache2 is running"
else
    echo "Failed to start apache2"
fi
